create table STATS
(
    STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(BESTSELLER)
FROM BOOKS;

USE KODILLA_COURSE;

create definer = root@localhost event UPDATE_BESTSELLERS on schedule
    every '1' MINUTE
        starts '2021-04-10 20:56:59'
    enable
    do
    BEGIN
        CALL UpdateBestSellers();
        INSERT INTO STATS(STAT_DATE, STAT, VALUE)  VALUE (CURTIME(),'BESTSELLERS', (SELECT * FROM BESTSELLERS_COUNT));
    END;