EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';

create index READERTNAME
    on readers (FIRSTNAME,LASTNAME);

create index BOOKTITLE
    on books (TITLE);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';
